config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    resources :snippets
  end
  get 'welcome/index'

  resources :snippets

  root 'welcome#index'

  

end

app/models/snippet.rb
class Snippet < ActiveRecord::Base
	validates :body, :presence => true
	def self.search(search)
	  where("body LIKE ?", "%#{search}%") 
	end
end

app/controllers/api/api_controller.rb
class Api::ApiController < ApplicationController
	  respond_to :json
end

app/controllers/api/snippets_controller.rb
class Api::SnippetsController < ApplicationController 
    def index
    	debugger 
    @snipptes = Snippet.all
    respond_to do |format|
      format.json { render json: @snipptes }
    end
  end

end

app/controllers/api/v1/api_controller.rb
class Api::V1::ApiController < ApplicationController
	  respond_to :json
end

app/controllers/api/v1/snippets_controller.rb
class Api::V1::SnippetsController < ApplicationController 
    respond_to :json
    def index
    @snipptes = Snippet.all
    respond_to do |format|
      format.json { render json: @snipptes }
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/snippets_controller.rb
class SnippetsController < ApplicationController
  def index
    @snipptes = Snippet.all
      if params[:search]
        @snipptes = Snippet.search(params[:search]).paginate(:page => params[:page], :per_page => 6).order('created_at DESC')
      else
        @snipptes = Snippet.paginate(:page => params[:page], :per_page => 6).order('created_at DESC')
      end
  end

  def new
  	@snippet = Snippet.new
  end

  def create
  	@snippet = Snippet.new(snippet_params)
  	respond_to do |format|
	  	if @snippet.save
	  		format.html  { redirect_to(@snippet,:notice => 'Snippet was successfully created.') }
	    else
	        format.html  { render :action => "new" }
	  	end
	end
  end
  def show
  	@snippet = Snippet.find(params[:id])
  end

  private 

   def snippet_params
   		params.require(:snippet).permit(:body, :status)
   end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/snippets_helper.rb
module SnippetsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SnippetApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/snippets/_form.html.erb
<%= form_for (@snippet) do |f|%>
	<% if @snippet.errors.any? %>
	  <div id="errorExplanation">
	    <h2><%= pluralize(@snippet.errors.count, "error") %> prohibited
	        this snippet from being saved:</h2>
	    <ul>
	    <% @snippet.errors.full_messages.each do |msg| %>
	      <li><%= msg %></li>
	    <% end %>
	    </ul>
	  </div>
	<% end %>
	<%= f.label :body, 'Create your snippet'%><br /><br />
	<%= f.text_area :body,:placeholder=>"some text input ...",:rows=>5, :cols=>50 %><br /><br />
	<%= f.check_box :status %>&nbsp; private? <br /><br />

	<%= f.submit "create"%>
<% end %>

app/views/snippets/index.html.erb
<div style="width:70%;">
	<span style="float:right;">
		<%= form_tag(snippets_path, :method => "get", id: "search-form") do %>
			<%= text_field_tag :search, params[:search], placeholder: "Search snippets" %>
		<% end %>
	</span>	
</div>
<br /><br /><br />
<div style="width:70%;">
	<span style="font-weight:bold;font-size:16px">Snippent</span>
	<span style="float:right;">
		<%= link_to "Create Snippet" , new_snippet_path %>
	</span>
</div>
<br />

<div style="width:70%;">
	<table border="1">
		<% @snipptes.each do |snippet|%>	
			<tr>				
				<td>
				<% if snippet.status == false %>
					<%= link_to snippet.body , snippet %>
				<% else %>
					<%= snippet.body %>
				<% end %>
				</td>
			</tr>	
		<% end %> 
	</table>
</div>
<%= will_paginate @snipptes %>

app/views/snippets/new.html.erb
<h2>New Snippet</h2>

<%= render "form"%>

app/views/snippets/show.html.erb
<%= @snippet.body.truncate(20) %>
<br />
<br />

<div style="border:2px solid #ccc;padding:10px;">
 <%= @snippet.body %>
</div>

<%= link_to "Back" ,snippets_path%>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

<%= link_to "Create Snippet", new_snippet_path %>